name: Release Docker Image 🚀

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/espresso-lab/oidc-forward-auth-middleware:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/espresso-lab/oidc-forward-auth-middleware:buildcache
          cache-to: type=registry,ref=ghcr.io/espresso-lab/oidc-forward-auth-middleware:buildcache,mode=max
